/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#3f4851",
        secondary: "#575f69",
        "on-tertiary-fixed": "#001e2b",
        "on-secondary-fixed": "#141c24",
        "secondary-fixed-dim": "#bfc7d2",
        "surface-container-low": "#f2f4f6",
        "primary-fixed": "#e5e2e1",
        "outline-variant": "#c4c7c7",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        "on-primary-fixed": "#1c1b1b",
        "inverse-surface": "#2d3133",
        tertiary: "#000000",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed-variant": "#164c63",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#c8c6c5",
        "on-surface-variant": "#444748",
        "surface-container": "#eceef0",
        "surface-tint": "#5f5e5e",
        "tertiary-container": "#001e2b",
        "secondary-container": "#dbe3ef",
        "on-secondary": "#ffffff",
        primary: "#000000",
        "tertiary-fixed": "#c2e8ff",
        background: "#f7f9fb",
        "on-tertiary-container": "#5a8aa3",
        "surface-dim": "#d8dadc",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "primary-fixed-dim": "#c8c6c5",
        "secondary-fixed": "#dbe3ef",
        "on-error": "#ffffff",
        surface: "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f7f9fb",
        "on-primary-fixed-variant": "#474646",
        "error-container": "#ffdad6",
        "on-secondary-container": "#5d656f",
        "tertiary-fixed-dim": "#9dcde9",
        outline: "#747878",
        "on-primary-container": "#858383",
        "primary-container": "#1c1b1b",
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e",
        "on-background": "#191c1e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        gutter: "1.5rem",
        "gutter-mobile": "1rem",
        margin: "3rem",
        "margin-mobile": "1.25rem",
      },
      fontFamily: {
        display: ["'Plus Jakarta Sans'", "'Inter'", "'Geist'", "sans-serif"],
        sans: ["'Plus Jakarta Sans'", "'Inter'", "'Geist'", "sans-serif"],
        headline: ["'Plus Jakarta Sans'", "'Inter'", "'Geist'", "sans-serif"],
        "headline-2xl": ["'Plus Jakarta Sans'", "'Inter'", "'Geist'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "'Inter'", "'Geist'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "'Inter'", "'Geist'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "'Inter'", "'Geist'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "'Inter'", "'Geist'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "'Inter'", "'Geist'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "'Inter'", "'Geist'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "'Inter'", "'Geist'", "sans-serif"],
        "label-md": ["'JetBrains Mono'", "monospace"],
        "label-sm": ["'JetBrains Mono'", "monospace"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
      keyframes: {
        fadeSlideIn: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-slide-in-1": "fadeSlideIn 0.6s ease-out forwards",
        "fade-slide-in-2": "fadeSlideIn 0.8s ease-out forwards",
        "fade-slide-in-3": "fadeSlideIn 1s ease-out forwards",
        "fade-slide-in-4": "fadeSlideIn 1.2s ease-out forwards",
      },
      fontSize: {
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "30px", letterSpacing: "-0.015em", fontWeight: "500" },
        ],
        "headline-2xl": [
          "72px",
          { lineHeight: "76px", letterSpacing: "-0.04em", fontWeight: "600" },
        ],
        "label-sm": [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "500" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" },
        ],
        "headline-xl": [
          "48px",
          { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "500" },
        ],
        "headline-sm": [
          "20px",
          { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
        "body-sm": [
          "13px",
          { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "body-md": [
          "15px",
          { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" },
        ],
        "headline-xl-mobile": [
          "32px",
          { lineHeight: "36px", letterSpacing: "-0.025em", fontWeight: "600" },
        ],
        "headline-2xl-mobile": [
          "40px",
          { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
